#!/usr/bin/env python3
"""
Self-host Google Fonts (Cairo + Inter) as woff2 files with unicode-range
subsetting preserved.

Fetches the css2 API, parses every @font-face block, downloads each woff2
into public/fonts/ and writes styles/fonts.css with rewritten local URLs.
No build-time network dependency afterwards.

Usage: python3 scripts/fetch-fonts.py
"""

import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "public" / "fonts"
CSS_OUT = ROOT / "styles" / "fonts.css"

FAMILIES = [
    ("Cairo", "wght@400..800"),
    ("Inter", "wght@400..800"),
]

CSS2_URL = "https://fonts.googleapis.com/css2?{families}&display=swap"
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0 Safari/537.36"
)


def fetch(url: str, binary: bool = False) -> str | bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = resp.read()
        return data if binary else data.decode("utf-8")


def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    families = "&".join(f"family={name}:{axis}" for name, axis in FAMILIES)
    css = fetch(CSS2_URL.format(families=families))

    blocks = re.findall(r"@font-face\s*\{[^}]+\}", css)
    if not blocks:
        raise SystemExit("No @font-face blocks found — css2 API response changed?")

    written = []
    counts: dict[str, int] = {}

    for block in blocks:
        fam = re.search(r"font-family:\s*['\"]?([^'\";]+)", block)
        weight = re.search(r"font-weight:\s*(\d+)", block)
        style = re.search(r"font-style:\s*(\w+)", block)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not (fam and url):
            continue

        family = fam.group(1).strip()
        w = weight.group(1) if weight else "400"
        s = style.group(1) if style else "normal"
        key = f"{family}-{w}"
        counts[key] = counts.get(key, 0) + 1
        fname = f"{family.replace(' ', '')}-{w}-{counts[key]}.woff2"
        fpath = FONT_DIR / fname

        if not fpath.exists():
            data = fetch(url.group(1), binary=True)
            assert isinstance(data, bytes)
            fpath.write_bytes(data)

        new_block = block.replace(url.group(1), f"/fonts/{fname}")
        new_block = new_block.replace("font-style: normal", f"font-style: {s}")
        written.append(new_block)

    css_out = (
        "/* Auto-generated by scripts/fetch-fonts.py — do not edit manually. */\n"
        "/* Self-hosted: Cairo (Arabic + Latin) & Inter (Latin). */\n\n"
        + "\n\n".join(written)
        + "\n"
    )
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.write_text(css_out, encoding="utf-8")

    files = sorted(p.name for p in FONT_DIR.iterdir() if p.suffix == ".woff2")
    print(f"OK: {len(written)} @font-face rules, {len(files)} woff2 files -> {CSS_OUT}")
    print("Fonts:", ", ".join(files))


if __name__ == "__main__":
    main()
