-- ═══════════════════════════════════════════════════════════════════════════
-- JOEX Teacher Website — demo seed content
-- Mirrors lib/data/seed/*.ts so the database matches preview mode exactly.
-- All content is clearly demo (testimonials is_demo = true, site_config
-- demo_mode = true) and is meant to be replaced from the teacher dashboard.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Site config (single row) ──────────────────────────────────────────────
insert into public.site_config (
  id, teacher_name_ar, teacher_name_en, teacher_title_ar, teacher_title_en,
  subject_ar, subject_en, city_ar, city_en, whatsapp, phone, email,
  address_ar, address_en, bio_ar, bio_en, photo_url,
  students_count, years_experience, success_rate, exams_count, demo_mode
) values (
  1,
  'أ/ كريم حسن', 'Mr. Karim Hassan',
  'مدرس رياضيات للمرحلة الثانوية', 'Secondary School Mathematics Teacher',
  'الرياضيات', 'Mathematics', 'القاهرة', 'Cairo',
  '+201001234567', '+201001234567', 'karim.hassan@joex-teacher.example',
  'القاهرة — مدينة نصر', 'Cairo — Nasr City',
  'أكثر من ٨ سنوات في تدريس الرياضيات لطلاب المرحلة الثانوية، أؤمن أن الرياضيات تُفهم ولا تُحفظ. أعتمد في الشرح على ربط الأفكار ببعضها والتدريب المنظم، مع متابعة مستمرة لكل طالب حتى يصل إلى أعلى مستوياته. (هذه نبذة تجريبية — يمكن تحديثها من لوحة التحكم)',
  'More than 8 years teaching mathematics to secondary school students. I believe mathematics is understood, not memorized — my lessons connect ideas, build from fundamentals, and follow each student with structured practice until they reach their full potential. (Demo bio — update from the dashboard)',
  '/images/teacher-portrait.png',
  2500, 8, 95, 120, true
);

-- ── Courses ───────────────────────────────────────────────────────────────
insert into public.courses (id, slug, subject_ar, subject_en, title_ar, title_en,
  description_ar, description_en, what_you_learn_ar, what_you_learn_en,
  grade, price, duration_weeks, image_url, status, featured, sort_order) values
('c-algebra-trig-1st', 'algebra-trig-1st-secondary', 'الرياضيات', 'Mathematics',
 'الجبر وحساب المثلثات — الصف الأول الثانوي', 'Algebra & Trigonometry — 1st Secondary',
 'تأسيس قوي في الجبر وحساب المثلثات: من الأعداد الحقيقية إلى الدوال والنسب المثلثية، بشرح يبني الفهم خطوة بخطوة مع تدريبات مكثفة.',
 'A solid foundation in algebra and trigonometry — from real numbers to functions and trig ratios, taught step by step with intensive practice.',
 '["الأعداد الحقيقية والقوى والجذور بمنطق واضح","حل المعادلات والمتباينات في متغير واحد","فهم الدوال وتمثيلها البياني","النسب المثلثية وحل المثلث القائم","التعامل مع المسائل المقالية بثقة"]',
 '["Real numbers, powers and roots — understood, not memorized","Solving linear equations and inequalities","Understanding functions and their graphs","Trigonometric ratios and solving right triangles","Tackling word problems with confidence"]',
 'الصف الأول الثانوي', 250, 12, '/images/cover-algebra.png', 'published', true, 1),

('c-geometry-1st', 'geometry-1st-secondary', 'الرياضيات', 'Mathematics',
 'الهندسة المستوية — الصف الأول الثانوي', 'Plane Geometry — 1st Secondary',
 'الزوايا والتوازي وتطابق وتشابه المثلثات والدائرة — هندسة تُفهم بالرسم والاستنتاج لا بالحفظ.',
 'Angles, parallel lines, triangle congruence and similarity, and circles — geometry learned through drawing and reasoning, not memorization.',
 '["العلاقات بين المستقيمات والزوايا","تطابق المثلثات وحالات التطابق","تشابه المثلثات ونظرية طاليس","الدائرة: الأوتار والزوايا المحيطية","بناء البراهين الهندسية خطوة بخطوة"]',
 '["Relations between lines and angles","Triangle congruence and its cases","Triangle similarity and Thales'' theorem","The circle: chords and inscribed angles","Building geometric proofs step by step"]',
 'الصف الأول الثانوي', 200, 10, '/images/cover-geometry.png', 'published', false, 2),

('c-algebra-geom-2nd', 'algebra-geometry-2nd-secondary', 'الرياضيات', 'Mathematics',
 'الجبر والهندسة الفراغية — الصف الثاني الثانوي', 'Algebra & Solid Geometry — 2nd Secondary',
 'الدوال الحقيقية والمتتابعات مع أساسيات الهندسة الفراغية — بشرح يركز على الربط بين الفروع.',
 'Real functions and sequences alongside the fundamentals of solid geometry — taught with a focus on how the branches connect.',
 '["الدوال الحقيقية وتصنيفها","المتتابعات الحسابية والهندسية","الأسس واللوغاريتمات","أساسيات الهندسة الفراغية والمستقيمات","المتجهات في الفراغ"]',
 '["Real functions and their classification","Arithmetic and geometric sequences","Exponents and logarithms","Fundamentals of solid geometry and lines","Vectors in space"]',
 'الصف الثاني الثانوي', 300, 12, '/images/cover-functions.png', 'published', false, 3),

('c-calculus-3rd', 'calculus-3rd-secondary', 'الرياضيات', 'Mathematics',
 'التفاضل والتكامل — الصف الثالث الثانوي', 'Calculus — 3rd Secondary',
 'النهايات والتفاضل وتطبيقاته والتكامل — أهم كورس لطلاب الثانوية العامة، بشرح يبني الفهم قبل الحفظ.',
 'Limits, differentiation, applications and integration — the most important course for Thanaweya Amma students, built on understanding first.',
 '["النهايات وقوانينها بفهم هندسي","قواعد الاشتقاق ومشتقات الدوال","تطبيقات التفاضل: المماس والسرعة والتغير","التكامل غير المحدد والمحدد","حل مسائل الامتحان بسرعة ودقة"]',
 '["Limits and their laws with geometric intuition","Differentiation rules and derivatives","Applications: tangents, rates of change and velocity","Indefinite and definite integrals","Solving exam questions quickly and accurately"]',
 'الصف الثالث الثانوي', 350, 14, '/images/cover-calculus.png', 'published', true, 4),

('c-algebra-solid-3rd', 'algebra-solid-geometry-3rd-secondary', 'الرياضيات', 'Mathematics',
 'الجبر والهندسة الفراغية — الصف الثالث الثانوي', 'Algebra & Solid Geometry — 3rd Secondary',
 'التوافيق والتباديل ونظرية ذات الحدين والاحتمالات مع الهندسة الفراغية — الكورس المكمل للتفاضل.',
 'Permutations, combinations, the binomial theorem, probability and solid geometry — the perfect companion to the calculus course.',
 '["مبدأ العد والتباديل والتوافيق","نظرية ذات الحدين","الاحتمالات وقوانينها","الزوايا والمسافات في الفراغ","حل أسئلة الامتحان بثقة"]',
 '["Counting principles, permutations and combinations","The binomial theorem","Probability and its laws","Angles and distances in space","Solving exam questions with confidence"]',
 'الصف الثالث الثانوي', 350, 12, '/images/cover-probability.png', 'published', false, 5),

('c-exam-mastery', 'final-exam-mastery', 'الرياضيات', 'Mathematics',
 'مراجعة نهائية وليلة الامتحان', 'Final Revision & Exam-Night Mastery',
 'مراجعة مكثفة لكل فروع الرياضيات: ملخصات سريعة، امتحانات تجريبية بوقت حقيقي، وخطط إدارة الوقت داخل الامتحان.',
 'Intensive revision across all math branches: rapid summaries, timed mock exams, and in-exam time-management strategies.',
 '["ملخص مركز لكل فروع المادة","امتحانات تجريبية بوقت الامتحان الفعلي","استراتيجيات إدارة الوقت داخل الامتحان","تحليل أخطاء الامتحانات السابقة","هدوء نفسي وثقة قبل الامتحان"]',
 '["A condensed summary of every branch","Mock exams timed to the real exam","In-exam time management strategies","Error analysis of past papers","Calm and confidence before the exam"]',
 'الصف الثالث الثانوي', 150, 6, '/images/cover-review.png', 'published', true, 6);

-- ── Lessons ───────────────────────────────────────────────────────────────
insert into public.lessons (id, course_id, title_ar, title_en, description_ar, description_en, duration_minutes, sort_order) values
('l-a1', 'c-algebra-trig-1st', 'أسس الجبر: الأعداد الحقيقية والقوى', 'Foundations: Real Numbers & Powers',
 'مراجعة الأعداد النسبية وغير النسبية، وقوانين القوى والجذور مع تطبيقات.',
 'Review of rational and irrational numbers, laws of powers and roots with applications.', 45, 1),
('l-a2', 'c-algebra-trig-1st', 'المعادلات والمتباينات في متغير واحد', 'Linear Equations & Inequalities',
 'طرق الحل الجبرية وتمثيل الحلول على خط الأعداد، مع مسائل لفظية.',
 'Algebraic solution methods, representing solutions on the number line, and word problems.', 50, 2),
('l-a3', 'c-algebra-trig-1st', 'الدوال وتمثيلها البياني', 'Functions & Their Graphs',
 'مفهوم الدالة، والتمثيل البياني، وتحديد مجال الدالة ومداها.',
 'The function concept, graphing, and finding domain and range.', 45, 3),
('l-a4', 'c-algebra-trig-1st', 'النسبة والتناسب وتطبيقاتهما', 'Ratio, Proportion & Applications',
 'قوانين النسبة والتناسب وحل مسائل التقسيم التناسبي.',
 'Ratio and proportion rules, solving proportional division problems.', 40, 4),
('l-a5', 'c-algebra-trig-1st', 'حساب المثلثات: النسب المثلثية الأساسية', 'Trigonometry: The Basic Ratios',
 'تعريف sin و cos و tan في المثلث القائم، وعلاقاتها الأساسية.',
 'Defining sin, cos and tan in a right triangle, with their core relationships.', 50, 5),
('l-a6', 'c-algebra-trig-1st', 'حل المثلث القائم وتطبيقات عملية', 'Solving Right Triangles & Applications',
 'إيجاد الأضلاع والزوايا المجهولة وتطبيقات على مسائل واقعية.',
 'Finding unknown sides and angles, applied to real-life problems.', 45, 6),

('l-g1', 'c-geometry-1st', 'المستقيمات والزوايا والعلاقات بينها', 'Lines, Angles & Their Relationships',
 'الزوايا المتتامة والمتكاملة، والزوايا الناتجة عن مستقيمين متوازيين وقاطع.',
 'Complementary and supplementary angles; angles formed by parallel lines and a transversal.', 45, 1),
('l-g2', 'c-geometry-1st', 'تطابق المثلثات', 'Triangle Congruence',
 'حالات التطابق الأربع وحل مسائل إثبات التطابق.',
 'The four congruence cases and proving congruent triangles.', 50, 2),
('l-g3', 'c-geometry-1st', 'تشابه المثلثات ونظرية طاليس', 'Triangle Similarity & Thales'' Theorem',
 'حالات التشابه وتطبيقات نظرية طاليس على الأضلاع.',
 'Similarity cases and applying Thales'' theorem to proportional sides.', 50, 3),
('l-g4', 'c-geometry-1st', 'الدائرة: الأوتار والزوايا', 'The Circle: Chords & Angles',
 'خصائص الأوتار والزوايا المحيطية والمركزية وعلاقاتها.',
 'Properties of chords, inscribed and central angles and their relationships.', 45, 4),
('l-g5', 'c-geometry-1st', 'تدريبات شاملة على البراهين', 'Comprehensive Proof Practice',
 'حل امتحانات سابقة على البراهين الهندسية بمختلف أنواعها.',
 'Solving past exam questions on geometric proofs of all types.', 55, 5),

('l-2-1', 'c-algebra-geom-2nd', 'الدوال الحقيقية وتصنيفها', 'Real Functions & Classification',
 'الدوال الزوجية والفردية، والدوال متعددة التعريف وتمثيلها.',
 'Even and odd functions, piecewise functions and their graphs.', 45, 1),
('l-2-2', 'c-algebra-geom-2nd', 'المتتابعات الحسابية والهندسية', 'Arithmetic & Geometric Sequences',
 'الحد العام والمجموع، وتطبيقات على مسائل واقعية.',
 'General terms and sums, applied to realistic problems.', 50, 2),
('l-2-3', 'c-algebra-geom-2nd', 'الأسس واللوغاريتمات', 'Exponents & Logarithms',
 'قوانين اللوغاريتمات وحل المعادلات اللوغاريتمية والأسية.',
 'Laws of logarithms, solving logarithmic and exponential equations.', 50, 3),
('l-2-4', 'c-algebra-geom-2nd', 'أساسيات الهندسة الفراغية', 'Fundamentals of Solid Geometry',
 'المستقيمات والمستويات في الفراغ وعلاقات التوازي والتعامد.',
 'Lines and planes in space; parallel and perpendicular relationships.', 45, 4),
('l-2-5', 'c-algebra-geom-2nd', 'المتجهات في الفراغ', 'Vectors in Space',
 'العمليات على المتجهات والضرب القياسي.',
 'Vector operations and the dot product.', 45, 5),
('l-2-6', 'c-algebra-geom-2nd', 'مراجعة وتدريبات شاملة', 'Comprehensive Review & Practice',
 'حل امتحانات على كامل المنهج.',
 'Solving full-curriculum exam papers.', 55, 6),

('l-c1', 'c-calculus-3rd', 'النهايات: المفهوم والقوانين', 'Limits: Concept & Laws',
 'المفهوم الهندسي للنهاية وقوانينها وحالات عدم التعيين.',
 'The geometric concept of limits, their laws, and indeterminate forms.', 50, 1),
('l-c2', 'c-calculus-3rd', 'قواعد الاشتقاق', 'Differentiation Rules',
 'مشتقة الدوال متعددة الحدود والجذرية والنسبية وقاعدة السلسلة.',
 'Derivatives of polynomial, radical and rational functions; the chain rule.', 50, 2),
('l-c3', 'c-calculus-3rd', 'مشتقات الدوال المثلثية', 'Derivatives of Trigonometric Functions',
 'مشتقات sin و cos و tan وتطبيقاتها في المسائل.',
 'Derivatives of sin, cos and tan, applied in exam-style problems.', 45, 3),
('l-c4', 'c-calculus-3rd', 'تطبيقات التفاضل', 'Applications of Differentiation',
 'معادلة المماس، ومعدلات التغير، والنقاط الحرجة.',
 'Tangent equations, rates of change, and critical points.', 50, 4),
('l-c5', 'c-calculus-3rd', 'التكامل غير المحدد والمحدد', 'Indefinite & Definite Integrals',
 'قواعد التكامل الأساسية والمساحة تحت المنحنى.',
 'Basic integration rules and the area under a curve.', 50, 5),
('l-c6', 'c-calculus-3rd', 'امتحانات تجريبية كاملة', 'Full Mock Exams',
 'حل امتحانات تجريبية شاملة بأسلوب الامتحان الرسمي مع تحليل الأخطاء.',
 'Full mock exams in official style with error analysis.', 60, 6),

('l-s1', 'c-algebra-solid-3rd', 'مبدأ العد الأساسي', 'The Fundamental Counting Principle',
 'مبدأ الضرب والجمع في العد وتمثيل الشجرة.',
 'The multiplication and addition principles, and tree diagrams.', 45, 1),
('l-s2', 'c-algebra-solid-3rd', 'التباديل والتوافيق', 'Permutations & Combinations',
 'الفرق بين الترتيب والاختيار وقوانين nPr و nCr.',
 'The difference between arrangement and selection; nPr and nCr.', 50, 2),
('l-s3', 'c-algebra-solid-3rd', 'نظرية ذات الحدين', 'The Binomial Theorem',
 'مفكوك ذات الحدين وإيجاد الحد العام.',
 'Binomial expansion and finding the general term.', 45, 3),
('l-s4', 'c-algebra-solid-3rd', 'الاحتمالات', 'Probability',
 'التعريف الكلاسيكي للاحتمال وحوادث الاتحاد والتقاطع.',
 'The classical definition of probability; union and intersection events.', 50, 4),
('l-s5', 'c-algebra-solid-3rd', 'الهندسة الفراغية والمسائل الشاملة', 'Solid Geometry & Comprehensive Problems',
 'الزوايا المجسمة والمسافات مع تدريبات امتحانية.',
 'Solid angles and distances with exam-style exercises.', 50, 5),

('l-r1', 'c-exam-mastery', 'مراجعة الجبر في ٣ حصص', 'Algebra Review in 3 Sessions',
 'الملخصات النهائية لكل باب في الجبر مع الأسئلة الأكثر تكرارًا.',
 'Final summaries of every algebra chapter with the most repeated questions.', 50, 1),
('l-r2', 'c-exam-mastery', 'مراجعة التفاضل والتكامل', 'Calculus Review',
 'أهم النقاط في التفاضل والتكامل والمسائل القصيرة المحببة في الامتحان.',
 'Key calculus points and the short-answer questions examiners love.', 50, 2),
('l-r3', 'c-exam-mastery', 'امتحان تجريبي شامل ١', 'Full Mock Exam 1',
 'امتحان كامل بنفس مواصفات الامتحان الرسمي مع تصحيح وتحليل الأخطاء.',
 'A complete exam matching the official specifications, graded with error analysis.', 60, 3),
('l-r4', 'c-exam-mastery', 'امتحان تجريبي شامل ٢ وليلة الامتحان', 'Full Mock Exam 2 & The Night Before',
 'امتحان ثانٍ وخطة الليلة الأخيرة: ماذا تراجع وماذا تترك.',
 'A second mock exam and the night-before plan: what to review and what to skip.', 60, 4);

-- ── Materials ─────────────────────────────────────────────────────────────
insert into public.materials (id, title_ar, title_en, description_ar, description_en,
  subject_ar, subject_en, grade, file_url, file_type, file_size_kb, upload_date, downloads, status) values
('m-1', 'ملخص الجبر الشامل — الصف الأول الثانوي', 'Complete Algebra Summary — 1st Secondary',
 'ملخص مركّز لكل أبواب الجبر: القوانين الأساسية، أمثلة محلولة، وأسئلة تدريبية بإجاباتها.',
 'A condensed summary of all algebra chapters: key laws, worked examples and practice questions with answers.',
 'الجبر', 'Algebra', 'الصف الأول الثانوي', '/demo-files/algebra-summary-1st.pdf', 'pdf', 2458, '2026-07-12', 184, 'published'),
('m-2', 'إجابات نموذجية — امتحان التفاضل', 'Model Answers — Calculus Exam',
 'الإجابات النموذجية لامتحان التفاضل والتكامل مع شرح خطوات الحل الكاملة لكل سؤال.',
 'Model answers for the calculus exam with full step-by-step solutions for every question.',
 'التفاضل والتكامل', 'Calculus', 'الصف الثالث الثانوي', '/demo-files/calculus-model-answers.pdf', 'pdf', 1875, '2026-07-20', 241, 'published'),
('m-3', 'قوانين حساب المثلثات — ورقة شاملة', 'Trigonometry Laws — Complete Sheet',
 'كل قوانين حساب المثلثات في ورقة واحدة: النسب، المتطابقات، وقوانين حل المثلث.',
 'Every trigonometry law on a single sheet: ratios, identities and triangle-solving rules.',
 'حساب المثلثات', 'Trigonometry', 'الصف الأول الثانوي', '/demo-files/trig-laws-sheet.pdf', 'pdf', 924, '2026-07-05', 312, 'published'),
('m-4', 'مراجعة ليلة الامتحان — الصف الثالث', 'Exam-Night Review — 3rd Secondary',
 'الملخص الأخير قبل الامتحان: أهم القوانين والنقاط الحرجة والأخطاء الشائعة التي يجب تجنبها.',
 'The final review before the exam: key laws, critical points and common mistakes to avoid.',
 'الرياضيات', 'Mathematics', 'الصف الثالث الثانوي', '/demo-files/exam-night-review.pdf', 'pdf', 3180, '2026-07-28', 428, 'published'),
('m-5', 'تمارين الدوال — مع الحلول الكاملة', 'Functions Exercises — With Full Solutions',
 'بنك تمارين على الدوال الحقيقية وتمثيلها البياني، مصنف حسب الصعوبة مع الحلول.',
 'An exercise bank on real functions and their graphs, graded by difficulty with solutions.',
 'الجبر', 'Algebra', 'الصف الثاني الثانوي', '/demo-files/functions-exercises.pdf', 'pdf', 1240, '2026-07-18', 156, 'published'),
('m-6', 'جداول مراجعة منتصف العام', 'Mid-Year Revision Schedule',
 'خطة مراجعة منظمة لامتحانات منتصف العام: ماذا تراجع كل يوم وكيف توزع وقتك.',
 'An organized revision plan for mid-year exams: what to review each day and how to manage your time.',
 'الرياضيات', 'Mathematics', 'كل الصفوف', '/demo-files/midyear-schedule.pdf', 'pdf', 742, '2026-06-30', 203, 'published');

-- ── Exams ─────────────────────────────────────────────────────────────────
insert into public.exams (id, title_ar, title_en, subject_ar, subject_en, grade,
  difficulty, duration_minutes, is_available, sort_order) values
('ex-algebra-1st', 'امتحان الجبر — الصف الأول الثانوي', 'Algebra Exam — 1st Secondary',
 'الجبر', 'Algebra', 'الصف الأول الثانوي', 'easy', 20, true, 1),
('ex-calculus-3rd', 'امتحان التفاضل والتكامل — الصف الثالث الثانوي', 'Calculus Exam — 3rd Secondary',
 'التفاضل والتكامل', 'Calculus', 'الصف الثالث الثانوي', 'medium', 30, true, 2),
('ex-review-comprehensive', 'امتحان شامل — مراجعة عامة', 'Comprehensive Review Exam',
 'الرياضيات', 'Mathematics', 'الصف الثالث الثانوي', 'hard', 25, true, 3);

insert into public.exam_questions (id, exam_id, question_ar, question_en,
  options_ar, options_en, correct_index, explanation_ar, explanation_en, sort_order) values
-- Algebra exam
('q-a1', 'ex-algebra-1st', 'ما قيمة المقدار 2³ × 2⁴؟', 'What is the value of 2³ × 2⁴?',
 '["2⁷","2¹²","4⁷","8¹²"]', '["2⁷","2¹²","4⁷","8¹²"]', 0,
 'عند ضرب قوى لها نفس الأساس نجمع الأسس: 2³ × 2⁴ = 2⁽³⁺⁴⁾ = 2⁷.',
 'When multiplying powers with the same base, add the exponents: 2³ × 2⁴ = 2⁽³⁺⁴⁾ = 2⁷.', 1),
('q-a2', 'ex-algebra-1st', 'إذا كان س + 5 = 12، فإن قيمة س = ؟', 'If x + 5 = 12, then x = ?',
 '["5","7","8","17"]', '["5","7","8","17"]', 1,
 'بطرح 5 من الطرفين: س = 12 − 5 = 7.', 'Subtract 5 from both sides: x = 12 − 5 = 7.', 2),
('q-a3', 'ex-algebra-1st', 'ما ميل المستقيم المار بالنقطتين (1، 2) و (3، 6)؟', 'What is the slope of the line through (1, 2) and (3, 6)?',
 '["1","2","3","4"]', '["1","2","3","4"]', 1,
 'الميل = (6 − 2) ÷ (3 − 1) = 4 ÷ 2 = 2.', 'Slope = (6 − 2) ÷ (3 − 1) = 4 ÷ 2 = 2.', 3),
('q-a4', 'ex-algebra-1st', 'ما قيمة جا ٣٠°؟', 'What is the value of sin 30°?',
 '["½","√3/2","1/√2","1"]', '["1/2","√3/2","1/√2","1"]', 0,
 'جا ٣٠° = ½ وهي من القيم المعروفة في المثلث الثلاثيني.',
 'sin 30° = 1/2, one of the standard values from the 30-60-90 triangle.', 4),
('q-a5', 'ex-algebra-1st', 'مجموعة حل المعادلة س² = 9 في ح هي:', 'The solution set of x² = 9 in R is:',
 '["{3}","{−3}","{−3، 3}","{9}"]', '["{3}","{−3}","{−3, 3}","{9}"]', 2,
 'بما أن (−3)² = 9 و (3)² = 9، فإن الحلين هما 3 و −3.',
 'Since (−3)² = 9 and (3)² = 9, both 3 and −3 are solutions.', 5),
('q-a6', 'ex-algebra-1st', 'إذا كانت د(س) = 2س + 1، فإن د(3) = ؟', 'If f(x) = 2x + 1, then f(3) = ?',
 '["5","6","7","8"]', '["5","6","7","8"]', 2,
 'بالتعويض: د(3) = 2 × 3 + 1 = 7.', 'Substitute: f(3) = 2 × 3 + 1 = 7.', 6),
('q-a7', 'ex-algebra-1st', 'في مثلث قائم الزاوية، إذا كان الوتر = 10 وأحد الضلعين = 6، فما طول الضلع الثالث؟',
 'In a right triangle with hypotenuse 10 and one leg 6, the other leg is:',
 '["6","7","8","9"]', '["6","7","8","9"]', 2,
 'بفيثاغورس: الضلع الآخر = √(10² − 6²) = √64 = 8 (مثلث 6-8-10).',
 'By Pythagoras: √(10² − 6²) = √64 = 8 (a 6-8-10 triangle).', 7),
('q-a8', 'ex-algebra-1st', 'أي من الأعداد التالية غير نسبي؟', 'Which of the following numbers is irrational?',
 '["3/4","√2","0.5","−7"]', '["3/4","√2","0.5","−7"]', 1,
 '√2 لا يمكن كتابته في صورة كسر اعتيادي، فهو عدد غير نسبي.',
 '√2 cannot be written as a fraction, so it is irrational.', 8),
-- Calculus exam
('q-c1', 'ex-calculus-3rd', 'قيمة نها(جا س ÷ س) عندما تؤول س إلى 0 تساوي:', 'lim(x→0) sin x / x equals:',
 '["0","1","∞","غير معرفة"]', '["0","1","∞","Undefined"]', 1,
 'هذه نهاية شهيرة: نها(جا س ÷ س) = 1 عندما تؤول س إلى صفر.',
 'This is the famous limit: lim(x→0) sin x / x = 1.', 1),
('q-c2', 'ex-calculus-3rd', 'مشتقة الدالة س³ تساوي:', 'The derivative of x³ is:',
 '["3س²","س²","3س","3س³"]', '["3x²","x²","3x","3x³"]', 0,
 'بقاعدة القوة: د/دس (سⁿ) = ن سⁿ⁻¹، إذن مشتقة س³ = 3س².',
 'By the power rule d/dx (xⁿ) = n·xⁿ⁻¹, so the derivative of x³ is 3x².', 2),
('q-c3', 'ex-calculus-3rd', 'مشتقة جا س تساوي:', 'The derivative of sin x is:',
 '["جتا س","−جتا س","−جا س","قا²س"]', '["cos x","−cos x","−sin x","sec²x"]', 0,
 'د/دس (جا س) = جتا س وهي قاعدة أساسية في التفاضل.',
 'd/dx (sin x) = cos x — a fundamental differentiation rule.', 3),
('q-c4', 'ex-calculus-3rd', '∫ 2س دس = ؟', '∫ 2x dx = ?',
 '["س² + ث","2س² + ث","س + ث","س²/2 + ث"]', '["x² + C","2x² + C","x + C","x²/2 + C"]', 0,
 'التكامل هو عكس الاشتقاق: مشتقة س² هي 2س، إذن ∫ 2س دس = س² + ث.',
 'Integration reverses differentiation: since d/dx(x²) = 2x, ∫ 2x dx = x² + C.', 4),
('q-c5', 'ex-calculus-3rd', 'ميل المماس لمنحنى ص = س² عند س = 1 يساوي:', 'The slope of the tangent to y = x² at x = 1 is:',
 '["0","1","2","4"]', '["0","1","2","4"]', 2,
 'المشتقة = 2س، وعند س = 1 يكون الميل = 2 × 1 = 2.',
 'The derivative is 2x; at x = 1 the slope is 2 × 1 = 2.', 5),
('q-c6', 'ex-calculus-3rd', 'قيمة نها (س² − 1) ÷ (س − 1) عندما تؤول س إلى 1 تساوي:', 'lim(x→1) (x² − 1)/(x − 1) equals:',
 '["0","1","2","∞"]', '["0","1","2","∞"]', 2,
 'بتحليل البسط: (س − 1)(س + 1) ÷ (س − 1) = س + 1، وعند س = 1 تكون النهاية 2.',
 'Factor the numerator: (x − 1)(x + 1)/(x − 1) = x + 1, which at x = 1 gives 2.', 6),
('q-c7', 'ex-calculus-3rd', 'إذا كانت د''(س) > 0 على فترة ما، فإن الدالة على هذه الفترة:', 'If f''(x) > 0 on an interval, then f is ______ on that interval.',
 '["متزايدة","متناقصة","ثابتة","غير معرفة"]', '["Increasing","Decreasing","Constant","Undefined"]', 0,
 'الإشارة الموجبة للمشتقة تعني أن الدالة متزايدة على هذه الفترة.',
 'A positive derivative means the function is increasing on that interval.', 7),
('q-c8', 'ex-calculus-3rd', 'قيمة ∫₀¹ س دس تساوي:', '∫₀¹ x dx equals:',
 '["0","½","1","2"]', '["0","1/2","1","2"]', 1,
 'التكامل المحدد = [س²/2] من 0 إلى 1 = ½ − 0 = ½.',
 'The definite integral is [x²/2] from 0 to 1 = 1/2 − 0 = 1/2.', 8),
('q-c9', 'ex-calculus-3rd', 'مشتقة الدالة هـˣ تساوي:', 'The derivative of eˣ is:',
 '["هـˣ","س هـˣ⁻¹","لط س","1/هـˣ"]', '["eˣ","x·eˣ⁻¹","ln x","1/eˣ"]', 0,
 'الدالة الأسية هـˣ هي الدالة الوحيدة التي تساوي مشتقتها نفسها.',
 'The exponential function eˣ is the only function equal to its own derivative.', 9),
('q-c10', 'ex-calculus-3rd', 'تصل الدالة إلى قيمة عظمى محلية عند نقطة إذا كانت المشتقة عندها:',
 'A function has a local maximum at a point where the derivative:',
 '["تساوي صفرًا وتتغير إشارتها من موجب إلى سالب","تساوي صفرًا وتتغير إشارتها من سالب إلى موجب","موجبة دائمًا","غير موجودة في كل الحالات"]',
 '["Is zero and changes from positive to negative","Is zero and changes from negative to positive","Is always positive","Is never defined"]', 0,
 'عند القيمة العظمى المحلية تمر الدالة من التزايد إلى التناقص، فتتغير إشارة المشتقة من موجب إلى سالب.',
 'At a local maximum the function goes from increasing to decreasing, so the derivative changes from positive to negative.', 10),
-- Comprehensive exam
('q-r1', 'ex-review-comprehensive', 'احتمال ظهور صورة عند رمي عملة معدنية سليمة مرة واحدة يساوي:',
 'The probability of getting heads when flipping a fair coin once is:',
 '["0","¼","½","1"]', '["0","1/4","1/2","1"]', 2,
 'النتائج الممكنة اثنتان متكافئتان: صورة أو كتابة، فاحتمال الصورة = ½.',
 'Two equally likely outcomes (heads/tails), so P(heads) = 1/2.', 1),
('q-r2', 'ex-review-comprehensive', 'الحد الخامس من المتتابعة الحسابية 2، 5، 8، ... يساوي:',
 'The 5th term of the arithmetic sequence 2, 5, 8, ... is:',
 '["11","14","17","20"]', '["11","14","17","20"]', 1,
 'الأساس = 3، والحد الخامس = 2 + 4 × 3 = 14.',
 'Common difference = 3; the 5th term = 2 + 4 × 3 = 14.', 2),
('q-r3', 'ex-review-comprehensive', 'قيمة جتا ٦٠° تساوي:', 'cos 60° equals:',
 '["½","√3/2","1/√2","0"]', '["1/2","√3/2","1/√2","0"]', 0,
 'جتا ٦٠° = ½ وهي قيمة قياسية يجب حفظها.',
 'cos 60° = 1/2, a standard value worth memorizing.', 3),
('q-r4', 'ex-review-comprehensive', 'عدد التباديل لثلاثة عناصر مختلفة تؤخذ جميعها معًا يساوي:',
 'The number of permutations of 3 distinct objects taken all at once is:',
 '["3","6","9","27"]', '["3","6","9","27"]', 1,
 '3! = 3 × 2 × 1 = 6 ترتيبًا مختلفًا.',
 '3! = 3 × 2 × 1 = 6 arrangements.', 4),
('q-r5', 'ex-review-comprehensive', 'حل المعادلة 2 جا س = 1 في الفترة [0، 2π) هو:',
 'The solution set of 2 sin x = 1 in [0, 2π) is:',
 '["س = π/6 فقط","س = π/6 ، 5π/6","س = π/3 ، 2π/3","س = π/2"]',
 '["x = π/6 only","x = π/6, 5π/6","x = π/3, 2π/3","x = π/2"]', 1,
 'جا س = ½ في الربعين الأول والثاني: س = π/6 أو 5π/6.',
 'sin x = 1/2 in the first and second quadrants: x = π/6 or 5π/6.', 5),
('q-r6', 'ex-review-comprehensive', 'حجم مكعب طول حرفه 3 سم يساوي:', 'The volume of a cube with edge 3 cm is:',
 '["9 سم³","18 سم³","27 سم³","81 سم³"]', '["9 cm³","18 cm³","27 cm³","81 cm³"]', 2,
 'حجم المكعب = (طول الحرف)³ = 3³ = 27 سم³.',
 'Volume = edge³ = 3³ = 27 cm³.', 6),
('q-r7', 'ex-review-comprehensive', 'ميل المستقيم الأفقي يساوي:', 'The slope of a horizontal line is:',
 '["0","1","غير معرف","−1"]', '["0","1","Undefined","−1"]', 0,
 'لا يوجد تغير في الصادي على مستقيم أفقي، فالميل = 0.',
 'There is no change in y along a horizontal line, so the slope is 0.', 7),
('q-r8', 'ex-review-comprehensive', 'إذا كان لو₁₀ 100 = س، فإن س يساوي:', 'If log₁₀ 100 = x, then x equals:',
 '["1","2","10","100"]', '["1","2","10","100"]', 1,
 '100 = 10²، إذن لو₁₀ 100 = 2.', '100 = 10², so log₁₀ 100 = 2.', 8),
('q-r9', 'ex-review-comprehensive', 'الوسط الحسابي للأعداد 4، 8، 6، 10، 12 يساوي:', 'The mean of 4, 8, 6, 10, 12 is:',
 '["6","7","8","10"]', '["6","7","8","10"]', 2,
 'المجموع = 40 والعدد 5 عناصر، إذن الوسط = 40 ÷ 5 = 8.',
 'Sum = 40 across 5 values, so the mean = 40 ÷ 5 = 8.', 9);

-- ── Testimonials (demo) ───────────────────────────────────────────────────
insert into public.testimonials (id, student_name_ar, student_name_en, grade,
  review_ar, review_en, rating, is_featured, is_demo, sort_order) values
('t-1', 'أحمد س.', 'Ahmed S.', 'الصف الثالث الثانوي',
 'كنت فاكر الرياضيات حفظ، لكن مع أ/ كريم فهمت الجبر لأول مرة. الشرح بيبدأ من الأساسيات خطوة بخطوة، والامتحانات الأونلاين ساعدتني أعرف مستواي الحقيقي قبل الامتحان.',
 'I used to think math was all memorization, but with Mr. Karim I finally understood algebra. The explanations build up step by step, and the online exams showed me exactly where I stood before the real exam.',
 5, true, true, 1),
('t-2', 'مريم ع.', 'Mariam A.', 'الصف الثاني الثانوي',
 'الحصص أونلاين منظمة جدًا، والمذكرات بتنزل بعد كل درس. حبيت إن في متابعة فعلية لحل الواجبات مش مجرد شرح وبس.',
 'The online lessons are very organized, and new materials are uploaded after every lesson. I love that homework is actually followed up on — it''s not just explanations and done.',
 5, true, true, 2),
('t-3', 'عمر خ.', 'Omar K.', 'الصف الأول الثانوي',
 'أول مرة أحس إن المسائل ليها منطق مش أرقام عشوائية. امتحانات المنصة صعبة شوية بس بتخليك جاهز لأي سؤال.',
 'First time I felt like math problems actually have logic instead of random numbers. The platform exams are a bit challenging, but they prepare you for anything.',
 4, false, true, 3),
('t-4', 'سارة م.', 'Sara M.', 'الصف الثالث الثانوي',
 'مراجعة ليلة الامتحان كانت نقطة التحول — امتحانات تجريبية بوقت حقيقي وشرح للأخطاء بالتفصيل. وصلت لدرجة حلمت بيها.',
 'The exam-night revision was a turning point — timed mock exams and detailed explanations of every mistake. I reached the score I''d dreamed of.',
 5, false, true, 4),
('t-5', 'يوسف ر.', 'Youssef R.', 'الصف الثاني الثانوي',
 'الحجز كان سهل جدًا — اخترت اليوم والموعد وأكدت في دقيقة، ووصلني تأكيد على واتساب فورًا. تعامل راقي من البداية.',
 'Booking was super easy — I picked the day and time and confirmed within a minute, and got an instant confirmation on WhatsApp. Professional from the very start.',
 5, false, true, 5),
('t-6', 'ليلى ح.', 'Laila H.', 'الصف الأول الثانوي',
 'والدتي كانت قلقة من المادة، لكن بعد شهرين من الحصص بقيت بحل المسائل بثقة. الشرح بالعربي والإنجليزي ساعدني كتير في المصطلحات.',
 'My mother was worried about the subject, but after two months of lessons I solve problems with confidence. The Arabic and English explanations really helped with the terminology.',
 4, false, true, 6);

-- ── FAQs ──────────────────────────────────────────────────────────────────
insert into public.faqs (id, question_ar, question_en, answer_ar, answer_en, sort_order) values
('faq-grades', 'ما الصفوف التي تُدرّسها؟', 'Which grades do you teach?',
 'أُدرّس مادة الرياضيات للصفوف الثلاثة من المرحلة الثانوية (الأول والثاني والثالث الثانوي)، في نظامي العربي والدولي، مع تركيز خاص على الاستعداد للامتحانات.',
 'I teach mathematics across all three secondary grades (1st, 2nd and 3rd), in both the Egyptian and international curricula, with a special focus on exam readiness.', 1),
('faq-format', 'هل الحصص أونلاين أم حضوري؟', 'Are the lessons online or in person?',
 'الحصص متاحة بالطريقتين: أونلاين عبر منصات الفيديو (Zoom / Meet) مع شاشة تفاعلية، أو حضوريًا في القاهرة (مدينة نصر). اختر ما يناسبك عند الحجز.',
 'Both. Lessons are available online via video platforms (Zoom / Meet) with an interactive whiteboard, or in person in Cairo (Nasr City). Choose whichever suits you when booking.', 2),
('faq-book', 'كيف أحجز حصة؟', 'How do I book a lesson?',
 'من صفحة «احجز حصتك» اختر الخدمة واليوم والموعد وأدخل بياناتك ثم أكّد الحجز — سأصلك رسالة على واتساب لتأكيد الموعد وترتيب التفاصيل.',
 'From the “Book a Lesson” page, choose a service, date and time, enter your details and confirm — you''ll receive a WhatsApp message to finalize the booking.', 3),
('faq-fees', 'ما هي أسعار الحصص؟', 'What are the fees?',
 'تختلف الأسعار حسب نوع الحصة (خاصة / مجموعة / مراجعات / اشتراك شهري). تظهر الأسعار التفصيلية في صفحات الكورسات، ويمكنك التواصل على واتساب للتعرف على العروض الحالية.',
 'Fees vary by lesson type (private / group / revision / monthly package). Detailed prices are shown on the course pages, and you can contact me on WhatsApp for current offers.', 4),
('faq-materials', 'هل المذكرات والملفات مشمولة؟', 'Are the materials included?',
 'نعم، يحصل كل طالب على مذكرات الشرح وملخصات المراجعة وإجابات النماذج بصيغة PDF من صفحة «المذكرات»، بالإضافة إلى الوصول للامتحانات الأونلاين وتصحيحها الفوري.',
 'Yes. Every student gets lesson notes, revision summaries and model answers as PDFs from the Materials page, plus access to online exams with instant grading.', 5),
('faq-examprep', 'هل تقدم مراجعات قبل الامتحانات؟', 'Do you offer exam revision?',
 'أوفر مراجعات مكثفة قبل امتحانات نصف العام والنهاية، مع امتحانات تجريبية شاملة على المنصة وشرح نموذج الإجابة بالتفصيل.',
 'Yes — intensive revision sessions before mid-year and final exams, plus full mock exams on the platform with detailed answer walkthroughs.', 6),
('faq-reschedule', 'هل يمكنني تغيير موعد الحصة؟', 'Can I reschedule a lesson?',
 'يمكنك تأجيل الحصة قبل موعدها بـ ٢٤ ساعة على الأقل عبر واتساب، وسيتم ترتيب موعد بديل يناسبك.',
 'You can reschedule up to 24 hours before the lesson via WhatsApp, and we''ll arrange a new time that suits you.', 7),
('faq-examsonline', 'كيف تعمل الامتحانات الأونلاين؟', 'How do the online exams work?',
 'الامتحانات بوقت محدد وتصحيح فوري: تبدأ الامتحان، وتُجيب على الأسئلة، وبعد التسليم تظهر درجتك ونسبة إجاباتك الصحيحة مع تقييم لأدائك. النتائج تُحفظ في حسابك إن كان لديك حساب.',
 'Exams are timed and auto-graded: start the exam, answer the questions, and upon submission you instantly see your score, accuracy and performance summary. Results are saved to your account when logged in.', 8);

-- ── Announcements ─────────────────────────────────────────────────────────
insert into public.announcements (id, title_ar, title_en, content_ar, content_en, is_published, published_at) values
('ann-1', 'استئناف الحصص بعد إجازة نصف العام', 'Lessons resume after the mid-year break',
 'أهلًا بالجميع 👋 نستأنف الحصص يوم السبت القادم بنفس الجداول. تم تحديث مواعيد المجموعات في صفحة الحجز، وراجعوا صفحة المذكرات لتحميل ملخصات الوحدات الجديدة قبل بداية الشرح.',
 'Welcome back 👋 Lessons resume next Saturday on the same schedule. Group times have been updated on the booking page — check the Materials page to download the new unit summaries before we begin.',
 true, '2026-08-15T09:00:00Z'),
('ann-2', 'امتحان جديد على المنصة', 'New exam available on the platform',
 'تمت إضافة امتحان «التفاضل والتكامل — الصف الثالث الثانوي» على صفحة الامتحانات. الامتحان بوقت محدد ٣٠ دقيقة، ويصوّب تلقائيًا فور التسليم. بالتوفيق!',
 'The “Calculus — 3rd Secondary” exam is now live on the Exams page. It''s timed (30 minutes) and auto-graded on submission. Good luck!',
 true, '2026-08-10T09:00:00Z'),
('ann-3', 'مراجعات ما قبل امتحانات نهاية العام', 'Final exam revision sessions',
 'تبدأ مراجعات نهاية العام يوم الأحد القادم: مراجعة شاملة لكل صفوف الثانوية مع امتحانات تجريبية على المنصة. أماكن المجموعات محدودة — احجز مبكرًا.',
 'Final revision sessions start next Sunday: full reviews for all secondary grades with mock exams on the platform. Group spots are limited — book early.',
 true, '2026-07-28T09:00:00Z');
